# Generated by Django 5.2.12 on 2026-05-04 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Email',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='Password',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='subCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=25)),
                ('coursearea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.coursearea')),
            ],
        ),
    ]
