# Generated by Django 6.0.2 on 2026-03-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='course_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achivement_standment', models.CharField(max_length=30)),
                ('Courses', models.CharField(max_length=30)),
                ('Teacher', models.ManyToManyField(to='MyApp1.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='cousres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('Course_Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.course_area')),
            ],
        ),
    ]
