# Generated by Django 6.0.2 on 2026-03-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_area',
            name='Teacher',
            field=models.ManyToManyField(to='MyApp1.teacher'),
        ),
    ]
