# Generated by Django 6.0.2 on 2026-04-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Area',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Course',
            field=models.ManyToManyField(to='MyApp1.coursearea'),
        ),
    ]
