# Generated by Django 6.0.2 on 2026-03-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_course_area_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_area',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='course_area',
            name='achivement_standment',
        ),
    ]
