# Generated by Django 6.0.2 on 2026-03-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_remove_teacher_id_alter_teacher_name_course_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Name',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='cousres',
        ),
    ]
