# Generated by Django 5.2.12 on 2026-05-04 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_teacher_email_teacher_password_subcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=25)),
                ('Accreditation', models.CharField(max_length=25)),
                ('UnitDescription', models.CharField(max_length=1000)),
                ('UnitGoals', models.CharField(max_length=1000)),
                ('ContentDescriptions', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.subcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('weight', models.CharField(max_length=25)),
                ('AssessmentTitle', models.CharField(max_length=25)),
                ('AssessmentUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.unit')),
            ],
        ),
    ]
