# Generated by Django 6.0.2 on 2026-03-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0003_teacher_id_alter_teacher_name_delete_cousres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_area',
            old_name='Achivement_standment',
            new_name='achivement_standment',
        ),
    ]
