# Generated by Django 6.0.2 on 2026-03-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0003_remove_course_area_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_area',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='course_area',
            name='Achivement_standment',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_area',
            name='Courses',
            field=models.CharField(default=1, verbose_name=1000),
            preserve_default=False,
        ),
    ]
