# Generated by Django 6.0.2 on 2026-03-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_rename_achivement_standment_course_area_achivement_standment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_area',
            name='Teacher',
        ),
    ]
