# Generated by Django 6.0.2 on 2026-03-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_remove_course_area_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_area',
            name='Achivement_standment',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='course_area',
            name='Courses',
            field=models.CharField(max_length=25),
        ),
    ]
