# Generated by Django 6.0.5 on 2026-05-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0004_teacher_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(limit_choices_to={'MyApp1.Course__coursearea__course': models.ManyToManyField(to='MyApp1.coursearea')}, to='MyApp1.unit'),
        ),
    ]
