# Generated by Django 6.0.2 on 2026-03-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0005_alter_course_area_achivement_standment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_area',
            name='Teacher',
            field=models.ManyToManyField(to='MyApp1.teacher'),
        ),
        migrations.AlterField(
            model_name='course_area',
            name='Achivement_standment',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course_area',
            name='Courses',
            field=models.CharField(max_length=30),
        ),
    ]
