# Generated by Django 6.0.2 on 2026-03-18 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0006_course_area_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cousres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('Course_Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp1.course_area')),
            ],
        ),
    ]
