# Generated by Django 6.0.2 on 2026-03-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0007_cousres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_area',
            old_name='Achivement_standment',
            new_name='achivement_standment',
        ),
        migrations.DeleteModel(
            name='cousres',
        ),
    ]
