# Generated by Django 6.0.2 on 2026-04-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0008_rename_achivement_standment_course_area_achivement_standment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_area',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='course_area',
            name='achivement_standment',
        ),
    ]
