# Generated by Django 6.0.2 on 2026-04-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0009_remove_course_area_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_Area',
        ),
    ]
